### ISSUE TITLE
Gestión de cuenta de usuario

### ISSUE THREAD

**Issue by luchanz** [luchanz/redhat-prode#2]
##### Gestión de cuenta de usuario
* Poder cambiar la clave (ahora no se puede, la cambiaban los admin por base de datos)
* Validación de cuenta (o un pequeño workflow que permite validar que sea empleado de la compañia, o validación a traves de regex por domino de empresa).
* Activación de la cuenta desde el mail (con mail de confirmación de signup)

##### Pendiente: Redhat debe definir la cuenta de redhat que va a ser la que envie los emails de activacion o cambio de clave.

**Comment by matiasciarla** [comment]
registracion

registra -> mail no existe | se crea en estado inactivo | manda mail
registra -> mail existe | esta inactivo | se crea / se deja en estado inactivo | manda mail
registra -> mail existe | esta activo | error

cambio de password

ingresa mail -> cuenta no existe | error
ingresa mail -> cuenta existe | cambia estado en revision_password | manda mail | el usuario entra al link | cambia password | cambia estado en cuenta activa.
ingresa al link de cambio password (encriptando usuario) | si el usuario esta en estado revision_password, puede cambiarla, si no error.

**Comment by matiasciarla** [comment]
Ver como va a ser el formato del mail que se va a enviar para activar usuario y para cambiar el password.

**Comment by matiasciarla** [comment]
Respuesta: agregar mail de confirmacion en la registracion
