### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by matiasciarla** [luchanz/redhat-prode#9]

**Comment by matiasciarla** [comment]
Porque se puede seguir votando en partidos que ya se jugaron

**Comment by luchanz** [comment]
Que html enviar en la confirmacion de cuenta y restart de password

**Comment by matiasciarla** [comment]
Como se van a dividir las fechas

**Comment by luchanz** [comment]
##### Gestión de cuenta de usuario (lógica)

##### Registracion

registra -> mail no existe | se crea en estado inactivo | manda mail
registra -> mail existe | esta inactivo | se crea / se deja en estado inactivo | manda mail
registra -> mail existe | esta activo | error

##### Cambio de password

ingresa mail -> cuenta no existe | error
ingresa mail -> cuenta existe | cambia estado en revision_password | manda mail | el usuario entra al link | cambia password | cambia estado en cuenta activa.
ingresa al link de cambio password (encriptando usuario) | si el usuario esta en estado revision_password, puede cambiarla, si no error.

**Comment by luchanz** [comment]
Token de seguridad?

**Comment by matiasciarla** [comment]
Definir que empresas van a participar y como se van a definir respecto al pais

**Comment by matiasciarla** [comment]
Respuesta: Chequear el offset... en la base tiene que estar el offset en 0 y desde angular cada cliente tiene que tener su offset. En caso de hackear ese offset, el request no debe ser valido

**Comment by matiasciarla** [comment]
Validar  email de requestParam con token sha al realizar un pronostico
